name: Phylogenetic

defaults:
  run:
    # This is the same as GitHub Action's `bash` keyword as of 20 June 2023:
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell
    #
    # Completely spelling it out here so that GitHub can't change it out from under us
    # and we don't have to refer to the docs to know the expected behavior.
    shell: bash --noprofile --norc -eo pipefail {0}

on:
  # This workflow will be triggered after the "Ingest" workflow has completed on the "main" branch.
  workflow_run:
    workflows:
      - Ingest
    types:
      - completed
    branches:
      - main

  workflow_dispatch:
    inputs:
      image:
        description: 'Specific container image to use for ingest workflow (will override the default of "nextstrain build")'
        required: false
        type: string
      trial_name:
        description: |
          Trial name for deploying builds.
          If not set, builds will overwrite existing builds at s3://nextstrain-data/norovirus*
          If set, builds will be deployed to s3://nextstrain-staging/norovirus_trials_<trial_name>_*
        required: false
        type: string
      sequences_url:
        description: |
          URL for a sequences.fasta.zst file.
          If not provided, will use default sequences_url from phylogenetic/defaults/config.yaml
        required: false
        type: string
      metadata_url:
        description: |
          URL for a metadata.tsv.zst file.
          If not provided, will use default metadata_url from phylogenetic/defaults/config.yaml
        required: false
        type: string

jobs:
  check-new-data:
    if: |
      github.event_name == 'workflow_run' &&
      github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.check-cache.outputs.cache-hit }}
    steps:
      - name: Get sha256sum
        id: get-sha256sum
        env:
          AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
        run: |
          s3_urls=(
            "s3://nextstrain-data/files/workflows/norovirus/metadata.tsv.zst"
            "s3://nextstrain-data/files/workflows/norovirus/sequences.fasta.zst"
          )

          # Code below is modified from ingest/upload-to-s3
          # https://github.com/nextstrain/ingest/blob/c0b4c6bb5e6ccbba86374d2c09b42077768aac23/upload-to-s3#L23-L29

          no_hash=0000000000000000000000000000000000000000000000000000000000000000

          for s3_url in "${s3_urls[@]}"; do
            s3path="${s3_url#s3://}"
            bucket="${s3path%%/*}"
            key="${s3path#*/}"

            s3_hash="$(aws s3api head-object --no-sign-request --bucket "$bucket" --key "$key" --query Metadata.sha256sum --output text 2>/dev/null || echo "$no_hash")"
            echo "${s3_hash}" | tee -a ingest-output-sha256sum
          done

      - name: Check cache
        id: check-cache
        uses: actions/cache@v5
        with:
          path: ingest-output-sha256sum
          key: ingest-output-sha256sum-${{ hashFiles('ingest-output-sha256sum') }}
          lookup-only: true

  phylogenetic:
    # Run the workflow under two conditions
    # 1. `workflow_run` triggered `check-new-data` and there's new data (no cache hit)
    # 2. the workflow is being manually run by `workflow_dispatch`
    needs: [check-new-data]
    if: |
      always() &&
      (
        (needs.check-new-data.result == 'success' && needs.check-new-data.outputs.cache-hit != 'true') ||
        github.event_name == 'workflow_dispatch'
      )
    permissions:
      id-token: write
    uses: nextstrain/.github/.github/workflows/pathogen-repo-build.yaml@master
    secrets: inherit
    with:
      # Starting with the default docker runtime
      # We can migrate to AWS Batch when/if we need to for more resources or if
      # the job runs longer than the GH Action limit of 6 hours.
      runtime: docker
      env: |
        NEXTSTRAIN_DOCKER_IMAGE: ${{ inputs.image }}
        TRIAL_NAME: ${{ inputs.trial_name }}
        SEQUENCES_URL: ${{ inputs.sequences_url }}
        METADATA_URL: ${{ inputs.metadata_url }}
      run: |
        declare -a config

        if [[ "$TRIAL_NAME" ]]; then
          config+=("deploy_url=s3://nextstrain-staging/norovirus_trials_${TRIAL_NAME}_")
        fi

        if [[ "$SEQUENCES_URL" ]]; then
          config+=("sequences_url=$SEQUENCES_URL")
        fi

        if [[ "$METADATA_URL" ]]; then
          config+=("metadata_url=$METADATA_URL")
        fi

        nextstrain build \
          phylogenetic \
            deploy_all \
            --configfile build-configs/nextstrain-automation/config.yaml \
            --keep-going \
            --config "${config[@]}"
      # Specifying artifact name to differentiate ingest build outputs from
      # the phylogenetic build outputs
      artifact-name: phylogenetic-build-output
      artifact-paths: |
        phylogenetic/auspice/
        phylogenetic/results/
        phylogenetic/benchmarks/
        phylogenetic/logs/
        phylogenetic/.snakemake/log/

  phylogenetic_genes:
    # Run the workflow under two conditions
    # 1. `workflow_run` triggered `check-new-data` and there's new data (no cache hit)
    # 2. the workflow is being manually run by `workflow_dispatch`
    needs: [check-new-data]
    if: |
      always() &&
      (
        (needs.check-new-data.result == 'success' && needs.check-new-data.outputs.cache-hit != 'true') ||
        github.event_name == 'workflow_dispatch'
      )
    permissions:
      id-token: write
    uses: nextstrain/.github/.github/workflows/pathogen-repo-build.yaml@master
    secrets: inherit
    with:
      # Starting with the default docker runtime
      # We can migrate to AWS Batch when/if we need to for more resources or if
      # the job runs longer than the GH Action limit of 6 hours.
      runtime: docker
      env: |
        NEXTSTRAIN_DOCKER_IMAGE: ${{ inputs.image }}
        TRIAL_NAME: ${{ inputs.trial_name }}
        SEQUENCES_URL: ${{ inputs.sequences_url }}
        METADATA_URL: ${{ inputs.metadata_url }}
      run: |
        declare -a config

        if [[ "$TRIAL_NAME" ]]; then
          config+=("deploy_url=s3://nextstrain-staging/norovirus_trials_${TRIAL_NAME}_")
        fi

        if [[ "$SEQUENCES_URL" ]]; then
          config+=("sequences_url=$SEQUENCES_URL")
        fi

        if [[ "$METADATA_URL" ]]; then
          config+=("metadata_url=$METADATA_URL")
        fi

        nextstrain build \
          phylogenetic \
            deploy_all \
            --configfile build-configs/nextstrain-automation/config.yaml defaults/all/config.yaml \
            --keep-going \
            --config "${config[@]}"
      # Specifying artifact name to differentiate ingest build outputs from
      # the phylogenetic build outputs
      artifact-name: phylogenetic_genes-build-output
      artifact-paths: |
        phylogenetic/auspice/
        phylogenetic/results/
        phylogenetic/benchmarks/
        phylogenetic/logs/
        phylogenetic/.snakemake/log/

  summary:
    runs-on: ubuntu-latest
    steps:
      - name: summary_step
        env:
          NEXTSTRAIN_DOCKER_IMAGE: ${{ inputs.image }}
          TRIAL_NAME: ${{ inputs.trial_name }}
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
        run: |
          if [[ "$TRIAL_NAME" ]]; then
              echo "### Trial Build URLs" >> $GITHUB_STEP_SUMMARY
              URL_BASE="https://nextstrain.org/staging/norovirus/trials"
              TRIAL_NAME_URL=$( echo "$TRIAL_NAME" | sed "s|_|/|g" )
              echo "" >> $GITHUB_STEP_SUMMARY
              echo "  * ${URL_BASE}/${TRIAL_NAME_URL}/norovirus/all/genome" >> $GITHUB_STEP_SUMMARY
              echo "  * ${URL_BASE}/${TRIAL_NAME_URL}/norovirus/all/VP1" >> $GITHUB_STEP_SUMMARY
              echo "  * ${URL_BASE}/${TRIAL_NAME_URL}/norovirus/all/RdRp" >> $GITHUB_STEP_SUMMARY
              echo "  * etc" >> $GITHUB_STEP_SUMMARY
          else
              echo "### Canonical URLs will be updated by this run" >> $GITHUB_STEP_SUMMARY
              URL_BASE="https://nextstrain.org/norovirus"
              echo "  * ${URL_BASE}/all/genome" >> $GITHUB_STEP_SUMMARY
              echo "  * ${URL_BASE}/all/VP1" >> $GITHUB_STEP_SUMMARY
              echo "  * ${URL_BASE}/all/RdRp" >> $GITHUB_STEP_SUMMARY
              echo "  * etc" >> $GITHUB_STEP_SUMMARY
          fi;
          echo "" >> $GITHUB_STEP_SUMMARY
          NOTE="NOTE: These URL paths may be incorrect if you've changed the  "
          NOTE+="snakemake targets in 'config/gisaid.yaml' as part of this PR. "
          NOTE+="Please update this GitHub Action if so!"
          echo "> $NOTE" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Build (meta-)environment"  >> $GITHUB_STEP_SUMMARY
          if [[ "$NEXTSTRAIN_DOCKER_IMAGE" ]]; then
              echo "  * Docker image: $NEXTSTRAIN_DOCKER_IMAGE" >> $GITHUB_STEP_SUMMARY
          else
              echo "  * Docker image: default (latest)" >> $GITHUB_STEP_SUMMARY
          fi;
          echo '  * Git Branch: `'"${BRANCH_NAME}"'`' >> $GITHUB_STEP_SUMMARY
